test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.719751ec9342e287d65f159349217fe0d498c294.name = "Upgrade from 0.6.2"